/**
 * Ponte entre os tokens CSS (src/index.css) e as variáveis de cor do Figma
 * KanDrive V0.2.1: coleção `Color` (modos Light e Dark), cujos papéis apontam
 * para a coleção `Primitives` (reestruturação de 2026-09-30).
 *
 * Os VALORES exibidos em Tokens/Colors são lidos do CSS em tempo de execução;
 * este arquivo guarda a correspondência de nomes, os valores do Figma para
 * comparação e a cor de base (`base`) de cada modo. Gerado a partir do Figma
 * (use_figma). Ao criar ou renomear um token, atualize aqui.
 */

export interface FigmaColor {
  light: string
  dark: string
  /** Cor de base em `Primitives` (com a opacidade, quando há), por modo. */
  lightBase?: string
  darkBase?: string
}

/** Papéis da coleção `Color` do Figma, valores resolvidos por modo. */
export const FIGMA_COLORS: Record<string, FigmaColor> = {
  "Border/Button/Ghost": { light: "#3f485026", dark: "#ffffff26", lightBase: "Slate/700 · 15%", darkBase: "Base/White · 15%" },
  "Border/Connector": { light: "#3f48504d", dark: "#ffffff4d", lightBase: "Slate/700 · 30%", darkBase: "Base/White · 30%" },
  "Border/Cool": { light: "#bec8cc", dark: "#48535a", lightBase: "Slate/200", darkBase: "Slate/675" },
  "Border/Default": { light: "#707070", dark: "#52525b", lightBase: "Gray/525", darkBase: "Zinc/650" },
  "Border/Ghost": { light: "#0000000f", dark: "#ffffff0f", lightBase: "Base/Black · 6%", darkBase: "Base/White · 6%" },
  "Border/Input": { light: "#8a8a93", dark: "#ffffff59", lightBase: "Zinc/450", darkBase: "Base/White · 35%" },
  "Border/Light": { light: "#bbbbbb", dark: "#3f3f46", lightBase: "Gray/250", darkBase: "Zinc/725" },
  "Border/Medium": { light: "#d4d4d4", dark: "#404040", lightBase: "Gray/150", darkBase: "Gray/725" },
  "Border/Soft": { light: "#e2e2e5", dark: "#3f3f46", lightBase: "Gray/100", darkBase: "Zinc/725" },
  "Border/Strong": { light: "#3a3a3a", dark: "#a1a1aa", lightBase: "Gray/750", darkBase: "Zinc/350" },
  "Border/Strong/Subtle": { light: "#3a3a3a38", dark: "#ffffff38", lightBase: "Gray/750 · 22%", darkBase: "Base/White · 22%" },
  "Border/Subtle": { light: "#ececf0", dark: "#ffffff1a", lightBase: "Zinc/50", darkBase: "Base/White · 10%" },
  "Brand/Accent/Dark": { light: "#b5254a", dark: "#d94f72", lightBase: "Pink/600", darkBase: "Pink/475" },
  "Brand/Accent/Light": { light: "#e8476a", dark: "#f27a95", lightBase: "Pink/450", darkBase: "Pink/350" },
  "Brand/Primary/Action": { light: "#007e96", dark: "#007e96", lightBase: "Teal/525", darkBase: "Teal/525" },
  "Brand/Primary/Action/Hover": { light: "#006b80", dark: "#006b80", lightBase: "Teal/650", darkBase: "Teal/650" },
  "Brand/Primary/Dark": { light: "#1a5e6e", dark: "#2391aa", lightBase: "Teal/775", darkBase: "Teal/450" },
  "Brand/Primary/Dark/Surface": { light: "#1a5e6e", dark: "#1a5e6e", lightBase: "Teal/775", darkBase: "Teal/775" },
  "Brand/Primary/Deep": { light: "#006579", dark: "#2391aa", lightBase: "Teal/725", darkBase: "Teal/450" },
  "Brand/Primary/Deep/Alt": { light: "#176a78", dark: "#2391aa", lightBase: "Teal/675", darkBase: "Teal/450" },
  "Brand/Primary/Default": { light: "#006579", dark: "#f3f3f3", lightBase: "Teal/725", darkBase: "Gray/50" },
  "Brand/Primary/Disabled": { light: "#ecfbfde6", dark: "#1a5e6e80", lightBase: "Teal/25 · 90%", darkBase: "Teal/775 · 50%" },
  "Brand/Primary/Foreground": { light: "#ffffff", dark: "#ffffff", lightBase: "Base/White", darkBase: "Base/White" },
  "Brand/Primary/Hover": { light: "#006b80", dark: "#eaeaea", lightBase: "Teal/650", darkBase: "Gray/75" },
  "Brand/Primary/Ink": { light: "#001f27", dark: "#c8dce3", lightBase: "Teal/900", darkBase: "Teal/150" },
  "Brand/Primary/Ink/20": { light: "#001f2733", dark: "#c8dce333", lightBase: "Teal/900 · 20%", darkBase: "Teal/150 · 20%" },
  "Brand/Primary/Light": { light: "#c8dce3", dark: "#c8dce3", lightBase: "Teal/150", darkBase: "Teal/150" },
  "Brand/Primary/Light/Surface": { light: "#c8dce3", dark: "#1a5e6e66", lightBase: "Teal/150", darkBase: "Teal/775 · 40%" },
  "Brand/Primary/Mid": { light: "#337084", dark: "#337084", lightBase: "Teal/575", darkBase: "Teal/575" },
  "Brand/Primary/Tint": { light: "#e0f0f2", dark: "#1a5e6e66", lightBase: "Teal/50", darkBase: "Teal/775 · 40%" },
  "Brand/Primary/Tint/Subtle": { light: "#ecfbfd", dark: "#1a5e6e33", lightBase: "Teal/25", darkBase: "Teal/775 · 20%" },
  "Brand/Secondary/Dark": { light: "#1a1714", dark: "#f5f4f2", lightBase: "Stone/925", darkBase: "Stone/50" },
  "Brand/Secondary/Default": { light: "#31302d", dark: "#c9c7c2", lightBase: "Stone/800", darkBase: "Stone/200" },
  "Brand/Secondary/Foreground": { light: "#ffffff", dark: "#1a1714", lightBase: "Base/White", darkBase: "Stone/925" },
  "Brand/Secondary/Light": { light: "#565652", dark: "#a8a6a1", lightBase: "Stone/650", darkBase: "Stone/325" },
  "Effect/Glass/Dark/20": { light: "#00000033", dark: "#ffffff33", lightBase: "Base/Black · 20%", darkBase: "Base/White · 20%" },
  "Effect/Glass/Frost/80": { light: "#f9f9f9cc", dark: "#1a1a1acc", lightBase: "Gray/25 · 80%", darkBase: "Gray/925 · 80%" },
  "Effect/Glass/Frost/90": { light: "#f9f9f9e6", dark: "#1a1a1ae6", lightBase: "Gray/25 · 90%", darkBase: "Gray/925 · 90%" },
  "Effect/Glass/Light/45": { light: "#f3f3f373", dark: "#26262673", lightBase: "Gray/50 · 45%", darkBase: "Gray/875 · 45%" },
  "Effect/Glass/Surface/Dark": { light: "#262626", dark: "#262626", lightBase: "Gray/875", darkBase: "Gray/875" },
  "Effect/Glass/Surface/Light": { light: "#ffffff99", dark: "#262626", lightBase: "Base/White · 60%", darkBase: "Gray/875" },
  "Effect/Glass/White/05": { light: "#ffffff0d", dark: "#1a1a1a0d", lightBase: "Base/White · 5%", darkBase: "Gray/925 · 5%" },
  "Effect/Glass/White/36": { light: "#ffffff5c", dark: "#1a1a1a5c", lightBase: "Base/White · 36%", darkBase: "Gray/925 · 36%" },
  "Effect/Glass/White/50": { light: "#ffffff80", dark: "#1a1a1a80", lightBase: "Base/White · 50%", darkBase: "Gray/925 · 50%" },
  "Effect/Glass/White/60": { light: "#ffffff99", dark: "#1a1a1a99", lightBase: "Base/White · 60%", darkBase: "Gray/925 · 60%" },
  "Effect/Glass/White/70": { light: "#ffffffb3", dark: "#1a1a1ab3", lightBase: "Base/White · 70%", darkBase: "Gray/925 · 70%" },
  "Effect/Overlay/Dark": { light: "#00000073", dark: "#ffffff73", lightBase: "Base/Black · 45%", darkBase: "Base/White · 45%" },
  "Effect/Overlay/Default": { light: "#00000080", dark: "#ffffff", lightBase: "Base/Black · 50%", darkBase: "Base/White" },
  "Effect/Overlay/Heavy": { light: "#000000d9", dark: "#ffffffd9", lightBase: "Base/Black · 85%", darkBase: "Base/White · 85%" },
  "Effect/Overlay/Light": { light: "#eaeaea99", dark: "#27272a99", lightBase: "Gray/75 · 60%", darkBase: "Gray/850 · 60%" },
  "Effect/Overlay/Medium": { light: "#00000024", dark: "#ffffff", lightBase: "Base/Black · 14%", darkBase: "Base/White" },
  "Effect/Overlay/Secondary": { light: "#6b6b6873", dark: "#a8a6a173", lightBase: "Stone/550 · 45%", darkBase: "Stone/325 · 45%" },
  "Effect/Overlay/Strong": { light: "#3a3a3ae6", dark: "#3a3a3ae6", lightBase: "Gray/750 · 90%", darkBase: "Gray/750 · 90%" },
  "Effect/Overlay/Subtle": { light: "#bfc7d21a", dark: "#a8b0bd26", lightBase: "Slate/225 · 10%", darkBase: "Slate/275 · 15%" },
  "Feedback/Danger/Default": { light: "#bc3426", dark: "#f07a6a", lightBase: "Red/575", darkBase: "Red/350" },
  "Feedback/Danger/Disabled": { light: "#bc34264d", dark: "#f07a6a4d", lightBase: "Red/575 · 30%", darkBase: "Red/350 · 30%" },
  "Feedback/Danger/Subtle": { light: "#bc342659", dark: "#e35d4a59", lightBase: "Red/575 · 35%", darkBase: "Red/425 · 35%" },
  "Feedback/Danger/Surface": { light: "#bc3426", dark: "#bc3426", lightBase: "Red/575", darkBase: "Red/575" },
  "Feedback/Success/Default": { light: "#009966", dark: "#34d399", lightBase: "Green/450", darkBase: "Green/250" },
  "Feedback/Success/Subtle": { light: "#00996659", dark: "#34d39959", lightBase: "Green/450 · 35%", darkBase: "Green/250 · 35%" },
  "Feedback/Success/Surface": { light: "#009966", dark: "#047857", lightBase: "Green/450", darkBase: "Green/550" },
  "Feedback/Warning/Default": { light: "#c38418", dark: "#f5b544", lightBase: "Amber/400", darkBase: "Amber/225" },
  "Feedback/Warning/Subtle": { light: "#f59e0b33", dark: "#f59e0b33", lightBase: "Amber/275 · 20%", darkBase: "Amber/275 · 20%" },
  "Feedback/Warning/Surface": { light: "#fff8e6", dark: "#3b2f12", lightBase: "Amber/25", darkBase: "Amber/800" },
  "Feedback/Warning/Surface/Alt": { light: "#fff8e6", dark: "#3b2f12", lightBase: "Amber/25", darkBase: "Amber/800" },
  "Feedback/Warning/Text": { light: "#80590d", dark: "#f5c35a", lightBase: "Amber/600", darkBase: "Amber/200" },
  "Focus/Ring": { light: "#92ccff", dark: "#92ccff", lightBase: "Blue/200", darkBase: "Blue/200" },
  "Icon/Default": { light: "#31302d", dark: "#e5e4e0", lightBase: "Stone/800", darkBase: "Stone/100" },
  "Logo/Glyph": { light: "#ffffff", dark: "#f5f4f2", lightBase: "Base/White", darkBase: "Stone/50" },
  "Logo/Symbol/Stop1": { light: "#007e96", dark: "#337084", lightBase: "Teal/525", darkBase: "Teal/575" },
  "Logo/Symbol/Stop2": { light: "#04798f", dark: "#2c6c7f", lightBase: "Teal/550", darkBase: "Teal/600" },
  "Logo/Symbol/Stop3": { light: "#0f6b7f", dark: "#236579", lightBase: "Teal/625", darkBase: "Teal/700" },
  "Logo/Symbol/Stop4": { light: "#1b5e6e", dark: "#1a5e6e", lightBase: "Teal/750", darkBase: "Teal/775" },
  "Logo/Wordmark/Accent": { light: "#007e96", dark: "#337084", lightBase: "Teal/525", darkBase: "Teal/575" },
  "Logo/Wordmark/Base": { light: "#31302d", dark: "#f5f4f2", lightBase: "Stone/800", darkBase: "Stone/50" },
  "Storage/FastAccess": { light: "#b5254a", dark: "#d94f72", lightBase: "Pink/600", darkBase: "Pink/475" },
  "Storage/FastAccess/Surface": { light: "#b5254a", dark: "#b5254a", lightBase: "Pink/600", darkBase: "Pink/600" },
  "Storage/LongTerm": { light: "#006579", dark: "#f3f3f3", lightBase: "Teal/725", darkBase: "Gray/50" },
  "Storage/LongTerm/Surface": { light: "#1a5e6e", dark: "#007e96", lightBase: "Teal/775", darkBase: "Teal/525" },
  "Storage/Ready": { light: "#d97706", dark: "#f59e0b", lightBase: "Amber/425", darkBase: "Amber/275" },
  "Surface/Background": { light: "#f3f3f3", dark: "#18181b", lightBase: "Gray/50", darkBase: "Gray/950" },
  "Surface/Background/Alt": { light: "#f3f3f3", dark: "#1c1c1f", lightBase: "Gray/50", darkBase: "Gray/900" },
  "Surface/Button/Secondary": { light: "#ffffffcc", dark: "#3f3f46cc", lightBase: "Base/White · 80%", darkBase: "Zinc/725 · 80%" },
  "Surface/Card": { light: "#ffffff", dark: "#222226", lightBase: "Base/White", darkBase: "Zinc/875" },
  "Surface/Cool/Strong": { light: "#6e797d", dark: "#9aa5a9", lightBase: "Slate/500", darkBase: "Slate/325" },
  "Surface/Cool/Subtle": { light: "#f3f3f3", dark: "#27272a", lightBase: "Gray/50", darkBase: "Gray/850" },
  "Surface/Elevated": { light: "#ffffff", dark: "#27272a", lightBase: "Base/White", darkBase: "Gray/850" },
  "Surface/Fixed/Dark/Base": { light: "#333333", dark: "#333333", lightBase: "Gray/800", darkBase: "Gray/800" },
  "Surface/Fixed/Dark/Deep": { light: "#282a2c", dark: "#282a2c", lightBase: "Zinc/825", darkBase: "Zinc/825" },
  "Surface/Fixed/Dark/Deeper": { light: "#1a1c1e", dark: "#1a1c1e", lightBase: "Zinc/900", darkBase: "Zinc/900" },
  "Surface/Fixed/Dark/Default": { light: "#222226", dark: "#222226", lightBase: "Zinc/875", darkBase: "Zinc/875" },
  "Surface/Fixed/Dark/Elevated": { light: "#262626", dark: "#262626", lightBase: "Gray/875", darkBase: "Gray/875" },
  "Surface/Fixed/Dark/Input": { light: "#333537", dark: "#333537", lightBase: "Zinc/775", darkBase: "Zinc/775" },
  "Surface/Fixed/Light": { light: "#f3f3f3", dark: "#f3f3f3", lightBase: "Gray/50", darkBase: "Gray/50" },
  "Surface/Ghost": { light: "#6b6b680d", dark: "#a8a6a10d", lightBase: "Stone/550 · 5%", darkBase: "Stone/325 · 5%" },
  "Surface/Ghost/Secondary": { light: "#6b6b681a", dark: "#a8a6a11a", lightBase: "Stone/550 · 10%", darkBase: "Stone/325 · 10%" },
  "Surface/Medium": { light: "#52525b", dark: "#a1a1aa", lightBase: "Zinc/650", darkBase: "Zinc/350" },
  "Surface/Muted": { light: "#71717a33", dark: "#a1a1aa33", lightBase: "Zinc/525 · 20%", darkBase: "Zinc/350 · 20%" },
  "Surface/Placeholder": { light: "#d4d4d4", dark: "#3a3a3a", lightBase: "Gray/150", darkBase: "Gray/750" },
  "Surface/Subtle": { light: "#eaeaea", dark: "#27272a", lightBase: "Gray/75", darkBase: "Gray/850" },
  "Surface/Subtle/Alt": { light: "#e2e2e5", dark: "#303036", lightBase: "Gray/100", darkBase: "Zinc/800" },
  "Text/Cool/Primary": { light: "#3e484c", dark: "#c5ced2", lightBase: "Slate/725", darkBase: "Slate/175" },
  "Text/Cool/Secondary": { light: "#475569", dark: "#cbd5e1", lightBase: "Slate/650", darkBase: "Slate/150" },
  "Text/Cool/Tertiary": { light: "#5a687b", dark: "#94a3b8", lightBase: "Slate/600", darkBase: "Slate/350" },
  "Text/Disabled": { light: "#ccced6", dark: "#92929b", lightBase: "Zinc/175", darkBase: "Zinc/400" },
  "Text/Fixed/Dark": { light: "#3f3f46", dark: "#3f3f46", lightBase: "Zinc/725", darkBase: "Zinc/725" },
  "Text/Fixed/Navy": { light: "#001d31", dark: "#001d31", lightBase: "Teal/925", darkBase: "Teal/925" },
  "Text/Ink": { light: "#000000", dark: "#ffffff", lightBase: "Base/Black", darkBase: "Base/White" },
  "Text/Ink/85": { light: "#000000d9", dark: "#ffffffd9", lightBase: "Base/Black · 85%", darkBase: "Base/White · 85%" },
  "Text/Muted": { light: "#68686e", dark: "#a1a1aa", lightBase: "Zinc/575", darkBase: "Zinc/350" },
  "Text/OnDark": { light: "#ffffff", dark: "#ffffff", lightBase: "Base/White", darkBase: "Base/White" },
  "Text/OnDark/Disabled": { light: "#ffffffcc", dark: "#ffffffcc", lightBase: "Base/White · 80%", darkBase: "Base/White · 80%" },
  "Text/OnGlass/Primary": { light: "#1a1a1a", dark: "#f3f3f3", lightBase: "Gray/925", darkBase: "Gray/50" },
  "Text/OnGlass/Secondary": { light: "#565652", dark: "#d4d4d8", lightBase: "Stone/650", darkBase: "Zinc/150" },
  "Text/OnGlass/Tertiary": { light: "#68686e", dark: "#a1a1aa", lightBase: "Zinc/575", darkBase: "Zinc/350" },
  "Text/Placeholder": { light: "#68686e", dark: "#a1a1aa", lightBase: "Zinc/575", darkBase: "Zinc/350" },
  "Text/Primary": { light: "#09090b", dark: "#ffffff", lightBase: "Gray/975", darkBase: "Base/White" },
  "Text/Secondary": { light: "#3f3f46", dark: "#d4d4d8", lightBase: "Zinc/725", darkBase: "Zinc/150" },
  "Text/Strong": { light: "#1a1a1a", dark: "#eaeaea", lightBase: "Gray/925", darkBase: "Gray/75" },
  "Text/Tertiary": { light: "#59595f", dark: "#a1a1aa", lightBase: "Zinc/625", darkBase: "Zinc/350" },
  "Feedback/Success/Text": { light: "#047857", dark: "#34d399", lightBase: "Green/550", darkBase: "Green/250" },
}

/** Token CSS → papel do Figma (o `codeSyntax` WEB de cada variável). */
export const CSS_TO_FIGMA: Record<string, string> = {
  "--brand-secondary-dark": "Brand/Secondary/Dark",
  "--brand-secondary": "Brand/Secondary/Default",
  "--brand-teal-dark": "Brand/Primary/Dark",
  "--brand-teal": "Brand/Primary/Default",
  "--brand-teal-light": "Brand/Primary/Light",
  "--brand-primary-disabled": "Brand/Primary/Disabled",
  "--brand-secondary-light": "Brand/Secondary/Light",
  "--destructive": "Feedback/Danger/Default",
  "--neutral-text-primary": "Text/Primary",
  "--neutral-text-secondary": "Text/Secondary",
  "--neutral-text-tertiary": "Text/Tertiary",
  "--neutral-border-default": "Border/Default",
  "--neutral-border-subtle": "Border/Subtle",
  "--neutral-surface-medium": "Surface/Medium",
  "--neutral-surface-subtle": "Surface/Subtle",
  "--neutral-surface-background": "Surface/Background",
  "--neutral-surface-card": "Surface/Card",
  "--brand-primary-mid": "Brand/Primary/Mid",
  "--neutral-text-placeholder": "Text/Placeholder",
  "--neutral-border-light": "Border/Light",
  "--effect-glass-dark-20": "Effect/Glass/Dark/20",
  "--effect-overlay-default": "Effect/Overlay/Default",
  "--neutral-surface-background-alt": "Surface/Background/Alt",
  "--effect-glass-light-45": "Effect/Glass/Light/45",
  "--effect-glass-white-50": "Effect/Glass/White/50",
  "--effect-glass-white-36": "Effect/Glass/White/36",
  "--effect-glass-white-70": "Effect/Glass/White/70",
  "--effect-overlay-light": "Effect/Overlay/Light",
  "--effect-overlay-subtle": "Effect/Overlay/Subtle",
  "--brand-primary-focus": "Focus/Ring",
  "--effect-glass-white-05": "Effect/Glass/White/05",
  "--effect-glass-surface-light": "Effect/Glass/Surface/Light",
  "--effect-glass-surface-dark": "Effect/Glass/Surface/Dark",
  "--neutral-surface-elevated": "Surface/Elevated",
  "--brand-pink-dark": "Brand/Accent/Dark",
  "--brand-pink-light": "Brand/Accent/Light",
  "--neutral-text-slate": "Text/Cool/Primary",
  "--neutral-border-cool": "Border/Cool",
  "--neutral-border-medium": "Border/Medium",
  "--neutral-border-zinc": "Border/Soft",
  "--neutral-text-ink-85": "Text/Ink/85",
  "--neutral-text-muted": "Text/Muted",
  "--neutral-slate-400": "Text/Cool/Tertiary",
  "--effect-glass-frost-80": "Effect/Glass/Frost/80",
  "--neutral-text-graphite": "Text/Strong",
  "--brand-primary-ink": "Brand/Primary/Ink",
  "--brand-primary-ink-20": "Brand/Primary/Ink/20",
  "--effect-glass-frost-90": "Effect/Glass/Frost/90",
  "--neutral-surface-gray": "Surface/Placeholder",
  "--effect-glass-white-60": "Effect/Glass/White/60",
  "--brand-primary-deep": "Brand/Primary/Deep",
  "--neutral-text-slate-600": "Text/Cool/Secondary",
  "--brand-feedback-warning-text": "Feedback/Warning/Text",
  "--brand-primary-teal-deep": "Brand/Primary/Deep/Alt",
  "--neutral-surface-steel": "Surface/Cool/Strong",
  "--neutral-icon-default": "Icon/Default",
  "--brand-teal-foreground": "Brand/Primary/Foreground",
  "--brand-teal-action": "Brand/Primary/Action",
  "--brand-teal-action-hover": "Brand/Primary/Action/Hover",
  "--storage-fast-access-surface": "Storage/FastAccess/Surface",
  "--storage-long-term-surface": "Storage/LongTerm/Surface",
  "--neutral-surface-constant-light": "Surface/Fixed/Light",
  "--neutral-text-constant-dark": "Text/Fixed/Dark",
  "--neutral-text-vibrant-primary": "Text/OnGlass/Primary",
  "--neutral-text-vibrant-secondary": "Text/OnGlass/Secondary",
  "--neutral-text-vibrant-tertiary": "Text/OnGlass/Tertiary",
  "--destructive-surface": "Feedback/Danger/Surface",
  "--brand-teal-dark-surface": "Brand/Primary/Dark/Surface",
  "--brand-feedback-success-surface": "Feedback/Success/Surface",
  "--brand-feedback-warning-surface": "Feedback/Warning/Surface",
  "--brand-secondary-foreground": "Brand/Secondary/Foreground",
  "--neutral-surface-button-secondary": "Surface/Button/Secondary",
  "--brand-primary-tint": "Brand/Primary/Tint",
  "--neutral-surface-subtle-cool": "Surface/Cool/Subtle",
  "--brand-feedback-warning-surface-alt": "Feedback/Warning/Surface/Alt",
  "--brand-primary-tint-subtle": "Brand/Primary/Tint/Subtle",
  "--brand-teal-light-surface": "Brand/Primary/Light/Surface",
  "--ui-input-border": "Border/Input",
  "--brand-feedback-success-text": "Feedback/Success/Text",
}
