/**
 * Ponte entre os tokens CSS (src/index.css) e as variáveis de cor do Figma
 * KanDrive V0.2.1 (coleção Core, modos Light e Dark).
 *
 * Os VALORES exibidos em Tokens/Colors são lidos do CSS em tempo de execução;
 * este arquivo só guarda a correspondência de nomes e os valores do Figma
 * para comparação. Gerado em 2026-09-24 a partir do Figma (use_figma) e
 * conferido: os pares batiam nos dois modos.
 * Ao criar ou renomear um token, atualize aqui.
 */

export interface FigmaColor {
  light: string
  dark: string
}

/** Variáveis de cor do Figma (Core), valores resolvidos por modo. */
export const FIGMA_COLORS: Record<string, FigmaColor> = {
  "Brand/Feedback/Danger/Default": { light: "#bc3426", dark: "#f07a6a" },
  "Brand/Feedback/Danger/Disabled": { light: "#bc34264d", dark: "#f07a6a4d" },
  "Brand/Feedback/Danger/Subtle": { light: "#c0392b59", dark: "#e35d4a59" },
  "Brand/Feedback/Danger/Surface": { light: "#bc3426", dark: "#bc3426" },
  "Brand/Feedback/Success/Default": { light: "#009966", dark: "#34d399" },
  "Brand/Feedback/Success/Subtle": { light: "#00996659", dark: "#34d39959" },
  "Brand/Feedback/Success/Surface": { light: "#009966", dark: "#047857" },
  "Brand/Feedback/Warning/Default": { light: "#c38418", dark: "#f5b544" },
  "Brand/Feedback/Warning/Subtle": { light: "#f59e0b33", dark: "#f59e0b33" },
  "Brand/Feedback/Warning/Surface": { light: "#fff8e6", dark: "#3b2f12" },
  "Brand/Feedback/Warning/Surface/Alt": { light: "#fffbeb", dark: "#3b2f12" },
  "Brand/Feedback/Warning/Text": { light: "#80590d", dark: "#f5c35a" },
  "Brand/Primary/Action": { light: "#007e96", dark: "#007e96" },
  "Brand/Primary/Action/Hover": { light: "#006b80", dark: "#006b80" },
  "Brand/Primary/Dark": { light: "#1a5e6e", dark: "#2391aa" },
  "Brand/Primary/Dark/Surface": { light: "#1a5e6e", dark: "#1a5e6e" },
  "Brand/Primary/Deep": { light: "#006377", dark: "#2391aa" },
  "Brand/Primary/Default": { light: "#007e96", dark: "#f5f5f5" },
  "Brand/Primary/Disabled": { light: "#ecfbfde5", dark: "#1a5e6e80" },
  "Brand/Primary/Focus": { light: "#92ccff", dark: "#92ccff" },
  "Brand/Primary/Foreground": { light: "#ffffff", dark: "#ffffff" },
  "Brand/Primary/Hover": { light: "#006b80", dark: "#e5e5e5" },
  "Brand/Primary/Ink": { light: "#001f27", dark: "#c8dce3" },
  "Brand/Primary/Ink/20": { light: "#001f2733", dark: "#c8dce333" },
  "Brand/Primary/Light": { light: "#c8dce3", dark: "#c8dce3" },
  "Brand/Primary/Light/Surface": { light: "#c8dce3", dark: "#1a5e6e66" },
  "Brand/Primary/Mid": { light: "#337084", dark: "#337084" },
  "Brand/Primary/Teal/Deep": { light: "#176a78", dark: "#2391aa" },
  "Brand/Primary/Tint": { light: "#e0f0f2", dark: "#1a5e6e66" },
  "Brand/Primary/Tint/Subtle": { light: "#eef9fa", dark: "#1a5e6e33" },
  "Brand/Secondary/Dark": { light: "#1a1714", dark: "#f5f4f2" },
  "Brand/Secondary/Default": { light: "#31302d", dark: "#c9c7c2" },
  "Brand/Secondary/Foreground": { light: "#ffffff", dark: "#1a1714" },
  "Brand/Secondary/Light": { light: "#6b6b68", dark: "#a8a6a1" },
  "Brand/Theme/Pink/Dark": { light: "#b5254a", dark: "#d94f72" },
  "Brand/Theme/Pink/Light": { light: "#e8476a", dark: "#f27a95" },
  "Effect/Glass/Dark/20": { light: "#00000033", dark: "#ffffff33" },
  "Effect/Glass/Fill/Light": { light: "#fafafa99", dark: "#262626" },
  "Effect/Glass/Frost/80": { light: "#f9f9f9cc", dark: "#1a1a1acc" },
  "Effect/Glass/Frost/90": { light: "#f9f9f9e5", dark: "#1a1a1ae5" },
  "Effect/Glass/Light/45": { light: "#f7f7f773", dark: "#2a2a2a73" },
  "Effect/Glass/Surface/Dark": { light: "#262626", dark: "#262626" },
  "Effect/Glass/Surface/Light": { light: "#fafafa99", dark: "#262626" },
  "Effect/Glass/White/05": { light: "#ffffff0d", dark: "#1a1a1a0d" },
  "Effect/Glass/White/36": { light: "#ffffff5c", dark: "#1a1a1a5c" },
  "Effect/Glass/White/50": { light: "#ffffff80", dark: "#1a1a1a80" },
  "Effect/Glass/White/60": { light: "#ffffff99", dark: "#1a1a1a99" },
  "Effect/Glass/White/70": { light: "#ffffffb3", dark: "#1a1a1ab2" },
  "Effect/Overlay/Dark": { light: "#00000073", dark: "#ffffff73" },
  "Effect/Overlay/Default": { light: "#00000080", dark: "#ffffff" },
  "Effect/Overlay/Heavy": { light: "#000000d9", dark: "#ffffffd9" },
  "Effect/Overlay/Light": { light: "#eaeaea99", dark: "#27272a99" },
  "Effect/Overlay/MD": { light: "#00000024", dark: "#ffffff" },
  "Effect/Overlay/Secondary": { light: "#6b6b6873", dark: "#a8a6a173" },
  "Effect/Overlay/Strong": { light: "#3a3a3ae5", dark: "#3a3a3ae5" },
  "Effect/Overlay/Subtle": { light: "#bfc7d21a", dark: "#a8b0bd26" },
  "Neutral/Border/Cool": { light: "#bec8cc", dark: "#48535a" },
  "Neutral/Border/Default": { light: "#707070", dark: "#52525b" },
  "Neutral/Border/Ghost": { light: "#0000000f", dark: "#ffffff0f" },
  "Neutral/Border/Light": { light: "#bbbbbb", dark: "#3f3f46" },
  "Neutral/Border/Medium": { light: "#d4d4d4", dark: "#404040" },
  "Neutral/Border/Strong": { light: "#3a3a3a", dark: "#a1a1aa" },
  "Neutral/Border/Strong/Subtle": { light: "#3a3a3a38", dark: "#ffffff38" },
  "Neutral/Border/Subtle": { light: "#ececf0", dark: "#ffffff1a" },
  "Neutral/Border/Zinc": { light: "#e4e4e7", dark: "#3f3f46" },
  "Neutral/Icon/Default": { light: "#32312e", dark: "#e5e4e0" },
  "Neutral/Slate/400": { light: "#94a3b8", dark: "#64748b" },
  "Neutral/Surface/Background": { light: "#f3f3f3", dark: "#18181b" },
  "Neutral/Surface/Background/Alt": { light: "#f7f7f7", dark: "#1c1c1f" },
  "Neutral/Surface/Button/Secondary": { light: "#ffffffcc", dark: "#3f3f46cc" },
  "Neutral/Surface/Card": { light: "#ffffff", dark: "#1f1f23" },
  "Neutral/Surface/Constant/Light": { light: "#f3f3f3", dark: "#f3f3f3" },
  "Neutral/Surface/Dark": { light: "#222226", dark: "#222226" },
  "Neutral/Surface/Dark/Base": { light: "#333333", dark: "#333333" },
  "Neutral/Surface/Dark/Deep": { light: "#282a2c", dark: "#282a2c" },
  "Neutral/Surface/Dark/Deeper": { light: "#1a1c1e", dark: "#1a1c1e" },
  "Neutral/Surface/Dark/Elevated": { light: "#262626", dark: "#262626" },
  "Neutral/Surface/Dark/Input": { light: "#333537", dark: "#333537" },
  "Neutral/Surface/Elevated": { light: "#ffffff", dark: "#27272a" },
  "Neutral/Surface/Ghost": { light: "#6b6b680d", dark: "#a8a6a10d" },
  "Neutral/Surface/Ghost/Map": { light: "#6b6b681a", dark: "#a8a6a11a" },
  "Neutral/Surface/Ghost/Secondary": { light: "#6b6b681a", dark: "#a8a6a11a" },
  "Neutral/Surface/Gray": { light: "#d9d9d9", dark: "#3a3a3a" },
  "Neutral/Surface/Medium": { light: "#52525b", dark: "#a1a1aa" },
  "Neutral/Surface/Muted": { light: "#71717a33", dark: "#a1a1aa33" },
  "Neutral/Surface/Steel": { light: "#6e797d", dark: "#9aa5a9" },
  "Neutral/Surface/Subtle": { light: "#eaeaea", dark: "#27272a" },
  "Neutral/Surface/Subtle/Alt": { light: "#e2e2e5", dark: "#303036" },
  "Neutral/Surface/Subtle/Cool": { light: "#f3f4f6", dark: "#27272a" },
  "Neutral/Text/Constant/Dark": { light: "#3f3f46", dark: "#3f3f46" },
  "Neutral/Text/Disabled": { light: "#ccced6", dark: "#92929b" },
  "Neutral/Text/Graphite": { light: "#1a1c1c", dark: "#ececec" },
  "Neutral/Text/Ink": { light: "#000000", dark: "#ffffff" },
  "Neutral/Text/Ink/85": { light: "#000000d9", dark: "#ffffffd9" },
  "Neutral/Text/Muted": { light: "#71717b", dark: "#a1a1aa" },
  "Neutral/Text/OnDark": { light: "#ffffff", dark: "#ffffff" },
  "Neutral/Text/OnDark/Deep": { light: "#001d31", dark: "#001d31" },
  "Neutral/Text/OnDark/Disabled": { light: "#ffffffcc", dark: "#ffffffcc" },
  "Neutral/Text/Placeholder": { light: "#bfc7d2", dark: "#a1a1aa" },
  "Neutral/Text/Primary": { light: "#09090b", dark: "#fafafa" },
  "Neutral/Text/Secondary": { light: "#3f3f46", dark: "#d4d4d8" },
  "Neutral/Text/Slate": { light: "#3e484c", dark: "#c5ced2" },
  "Neutral/Text/Slate/600": { light: "#475569", dark: "#cbd5e1" },
  "Neutral/Text/Tertiary": { light: "#71717a", dark: "#a1a1aa" },
  "Neutral/Text/Vibrant/Primary": { light: "#1a1a1a", dark: "#f5f5f5" },
  "Neutral/Text/Vibrant/Secondary": { light: "#727272", dark: "#d4d4d8" },
  "Neutral/Text/Vibrant/Tertiary": { light: "#bfbfbf", dark: "#a1a1aa" },
  "Storage/FastAccess": { light: "#e8476a", dark: "#e8476a" },
  "Storage/FastAccess/Surface": { light: "#b5254a", dark: "#b5254a" },
  "Storage/LongTerm": { light: "#007e96", dark: "#f5f5f5" },
  "Storage/LongTerm/Surface": { light: "#1a5e6e", dark: "#007e96" },
  "Storage/Ready": { light: "#d97706", dark: "#f59e0b" },
  "UI/Button/Border/Ghost": { light: "#3f485026", dark: "#ffffff26" },
  "UI/Connector/Border": { light: "#3f48504d", dark: "#ffffff4d" },
  "UI/Input/Border": { light: "#3f4850", dark: "#ffffff26" },
}

/** Token CSS → variável Figma. Tokens sem entrada não existem no Figma. */
export const CSS_TO_FIGMA: Record<string, string> = {
  "--neutral-text-primary": "Neutral/Text/Primary",
  "--neutral-text-secondary": "Neutral/Text/Secondary",
  "--neutral-surface-subtle": "Neutral/Surface/Subtle",
  "--neutral-border-light": "Neutral/Border/Light",
  "--destructive": "Brand/Feedback/Danger/Default",
  "--brand-teal": "Brand/Primary/Default",
  "--brand-teal-foreground": "Brand/Primary/Foreground",
  "--brand-teal-dark": "Brand/Primary/Dark",
  "--brand-secondary": "Brand/Secondary/Default",
  "--brand-pink-dark": "Brand/Theme/Pink/Dark",
  "--brand-pink-light": "Brand/Theme/Pink/Light",
  "--brand-teal-light": "Brand/Primary/Light",
  "--brand-teal-light-surface": "Brand/Primary/Light/Surface",
  "--brand-secondary-dark": "Brand/Secondary/Dark",
  "--brand-secondary-light": "Brand/Secondary/Light",
  "--effect-glass-light-45": "Effect/Glass/Light/45",
  "--effect-glass-white-70": "Effect/Glass/White/70",
  "--effect-glass-white-50": "Effect/Glass/White/50",
  "--effect-glass-white-36": "Effect/Glass/White/36",
  "--effect-glass-white-05": "Effect/Glass/White/05",
  "--effect-glass-dark-20": "Effect/Glass/Dark/20",
  "--effect-glass-surface-light": "Effect/Glass/Surface/Light",
  "--effect-glass-surface-dark": "Effect/Glass/Surface/Dark",
  "--effect-overlay-subtle": "Effect/Overlay/Subtle",
  "--neutral-surface-background": "Neutral/Surface/Background",
  "--neutral-border-default": "Neutral/Border/Default",
  "--brand-teal-action": "Brand/Primary/Action",
  "--brand-teal-action-hover": "Brand/Primary/Action/Hover",
  "--brand-teal-dark-surface": "Brand/Primary/Dark/Surface",
  "--destructive-surface": "Brand/Feedback/Danger/Surface",
  "--storage-fast-access-surface": "Storage/FastAccess/Surface",
  "--storage-long-term-surface": "Storage/LongTerm/Surface",
  "--brand-feedback-success-surface": "Brand/Feedback/Success/Surface",
  "--brand-feedback-warning-surface": "Brand/Feedback/Warning/Surface",
  "--brand-feedback-warning-surface-alt": "Brand/Feedback/Warning/Surface/Alt",
  "--brand-secondary-foreground": "Brand/Secondary/Foreground",
  "--neutral-surface-button-secondary": "Neutral/Surface/Button/Secondary",
  "--brand-primary-tint": "Brand/Primary/Tint",
  "--brand-primary-tint-subtle": "Brand/Primary/Tint/Subtle",
  "--neutral-surface-subtle-cool": "Neutral/Surface/Subtle/Cool",
  "--neutral-surface-constant-light": "Neutral/Surface/Constant/Light",
  "--neutral-text-constant-dark": "Neutral/Text/Constant/Dark",
  "--neutral-text-vibrant-primary": "Neutral/Text/Vibrant/Primary",
  "--neutral-text-vibrant-secondary": "Neutral/Text/Vibrant/Secondary",
  "--neutral-text-vibrant-tertiary": "Neutral/Text/Vibrant/Tertiary",
  "--neutral-text-slate": "Neutral/Text/Slate",
  "--neutral-text-slate-600": "Neutral/Text/Slate/600",
  "--neutral-text-muted": "Neutral/Text/Muted",
  "--neutral-text-graphite": "Neutral/Text/Graphite",
  "--neutral-text-ink-85": "Neutral/Text/Ink/85",
  "--neutral-icon-default": "Neutral/Icon/Default",
  "--neutral-border-cool": "Neutral/Border/Cool",
  "--neutral-border-medium": "Neutral/Border/Medium",
  "--neutral-border-zinc": "Neutral/Border/Zinc",
  "--neutral-slate-400": "Neutral/Slate/400",
  "--neutral-surface-gray": "Neutral/Surface/Gray",
  "--neutral-surface-steel": "Neutral/Surface/Steel",
  "--brand-primary-ink": "Brand/Primary/Ink",
  "--brand-primary-ink-20": "Brand/Primary/Ink/20",
  "--brand-primary-deep": "Brand/Primary/Deep",
  "--brand-primary-teal-deep": "Brand/Primary/Teal/Deep",
  "--brand-feedback-warning-text": "Brand/Feedback/Warning/Text",
  "--effect-glass-frost-80": "Effect/Glass/Frost/80",
  "--effect-glass-frost-90": "Effect/Glass/Frost/90",
  "--effect-glass-white-60": "Effect/Glass/White/60",
}
